triggers:
  - type: meya.regex
    properties:
        ignorecase: true
        pattern: ^(unsubscribe)|(cancel)$
states:
    unsubscribe:
        component: meya.unset
        properties:
            key: subscribed
            scope: user
    success:
        component: meya.text
        properties:
            text: |
                Sad to you see you go. 😢
                If you miss me, you can resubscribe by typing "subscribe" any time.
        return: true